### ISSUE TITLE
RuntimeException: class <SlidingDrawer> not found

### ISSUE THREAD

**Issue by evasyuk** [Ali-Rezaei/SlidingDrawer#1]
Android Studio 1.2.2, JDK 1.7, ASDK target API 22, ASDK min API 15
added
  compile 'com.github.ali-rezaei.android.client.customview:sliding-drawer:0.1.0'
to my build.gradle
added com.github.ali.android.client.customview.view.SlidingDrawer to layout as described in ReadMe
and this is log of crashing:
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hypewise/com.hypewise.base.activities.MainActivity}: android.view.InflateException: Binary XML file line #27: Error inflating class com.github.ali.android.client.customview.view.SlidingDrawer
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5022)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class com.github.ali.android.client.customview.view.SlidingDrawer
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.hypewise.base.activities.MainActivity.onCreate(MainActivity.java:177)
            at android.app.Activity.performCreate(Activity.java:5032)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5022)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: com.github.ali.android.client.customview.view.SlidingDrawer
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at android.view.LayoutInflater.createView(LayoutInflater.java:552)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.hypewise.base.activities.MainActivity.onCreate(MainActivity.java:177)
            at android.app.Activity.performCreate(Activity.java:5032)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5022)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
            at dalvik.system.NativeStart.main(Native Method)

Any suggestions?

**Comment by Ali-Rezaei** [comment]
Do you get the library in External Libraries folder under your project when you sync gradle?
Give a try to new release : compile 'com.github.ali-rezaei.android.client.customview:sliding-drawer:0.1.2'
